using FluentAssertions;
using FluentValidation;
using PawTrack.Application.Auth.Commands.VerifyEmail;

namespace PawTrack.UnitTests.Security;

/// <summary>
/// Round-45 security regression tests.
///
/// Gap: <c>VerifyEmailCommandValidator</c> uses <c>Length(32)</c> (FluentValidation
/// <c>ExactLengthValidator</c>) to validate the <c>Token</c> field:
///
///   <code>
///   RuleFor(x => x.Token)
///       .NotEmpty()
///       .Length(32).WithMessage("Invalid verification token format.");
///   </code>
///
/// The real token is generated by <c>User.Create()</c> as:
///
///   <code>
///   var bytes = RandomNumberGenerator.GetBytes(32);
///   var token = Convert.ToBase64String(bytes)        // 44 chars
///                   .TrimEnd('=')                    // 43 chars
///                   .Replace('+', '-')               // URL-safe
///                   .Replace('/', '_');
///   </code>
///
/// 32 raw bytes → 44 base64 chars → trim 1 trailing <c>=</c> → <b>43 characters</b>.
/// <c>FluentValidation.Length(32)</c> means <em>exactly</em> 32 characters.
///
/// Every real verification link contains a 43-character token, so every
/// <c>POST /api/auth/verify-email</c> returns 422 with "Invalid verification
/// token format." — email verification is functionally broken.
///
/// Secondary issue: the existing rule does not validate the character set,
/// so a 32-character token containing arbitrary bytes (e.g., injection chars)
/// passes validation.
///
/// Fix:
///   Replace <c>Length(32)</c> with <c>MaximumLength(64)</c>
///   and <c>Matches(@"^[A-Za-z0-9_-]+$")</c>.
///   This accepts any URL-safe base64 token (43–64 chars) while rejecting
///   tokens with illegal characters.
/// </summary>
public sealed class Round45SecurityRegressionTests
{
    private readonly VerifyEmailCommandValidator _sut = new();

    [Fact]
    public void Validator_AcceptsValidFortyThreeCharBase64Token()
    {
        // A real token from User.Create() is 43 URL-safe base64 chars
        const string realToken =
            "dGVzdC10b2tlbi10aGF0LWlzLTQzLWNoYXJzLWxvbmc"; // 43 chars, URL-safe base64

        var result = _sut.Validate(new VerifyEmailCommand(realToken));

        result.IsValid.Should().BeTrue(
            "a 43-character URL-safe base64 token is the exact format produced by User.Create() " +
            "and must not be rejected by the validator");
    }

    [Fact]
    public void Validator_RejectsTokenContainingInvalidCharacters()
    {
        // A 32-char string with an illegal character (@ is not in URL-safe base64)
        const string malformedToken = "valid-base64-but-has-@-sign-hello"; // 33 chars with @

        var result = _sut.Validate(new VerifyEmailCommand(malformedToken));

        result.IsValid.Should().BeFalse(
            "tokens containing characters outside URL-safe base64 alphabet " +
            "cannot be valid verification tokens and must be rejected");

        result.Errors.Should().Contain(e =>
            e.PropertyName == nameof(VerifyEmailCommand.Token),
            "the Token field must carry the validation error");
    }

    [Fact]
    public void Validator_RejectsEmptyToken()
    {
        var result = _sut.Validate(new VerifyEmailCommand(string.Empty));

        result.IsValid.Should().BeFalse();
        result.Errors.Should().Contain(e => e.PropertyName == nameof(VerifyEmailCommand.Token));
    }

    [Fact]
    public void Validator_RejectsExcessivelyLongToken()
    {
        // Anything over 64 chars is not a valid URL-safe base64 token from our generator
        var longToken = new string('a', 65);

        var result = _sut.Validate(new VerifyEmailCommand(longToken));

        result.IsValid.Should().BeFalse(
            "tokens longer than 64 characters cannot be valid and may indicate " +
            "a padding/buffer-overflow attempt");
    }
}
