/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core'
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { NetworkFirst } from 'workbox-strategies'

declare const self: ServiceWorkerGlobalScope

// ── Workbox boilerplate ───────────────────────────────────────────────────────

clientsClaim()
self.skipWaiting()
cleanupOutdatedCaches()

// Inject the pre-cache manifest generated by vite-plugin-pwa.
// eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
precacheAndRoute(self.__WB_MANIFEST)

// Cache API calls with a network-first strategy.
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({ cacheName: 'api-cache' }),
)

// ── Push notification handler ─────────────────────────────────────────────────

interface PushPayload {
  title: string
  body: string
  /** Deep-link to open when the notification is tapped (e.g. /p/{petId}). */
  url?: string
  /** Optional resolve-check notification id for action routing. */
  resolveCheckNotificationId?: string
}

self.addEventListener('push', (event: PushEvent) => {
  if (!event.data) return

  let payload: PushPayload

  try {
    payload = event.data.json() as PushPayload
  } catch {
    payload = { title: 'PawTrack CR', body: event.data.text() }
  }

  const { title, body, url, resolveCheckNotificationId } = payload

  const actions = resolveCheckNotificationId
    ? [
        { action: 'resolve-yes', title: 'Sí, ya está en casa' },
        { action: 'resolve-no', title: 'No, sigue perdido' },
      ]
    : undefined

  event.waitUntil(
    self.registration.showNotification(title, {
      body,
      icon: '/pwa-192x192.png',
      badge: '/pwa-192x192.png',
      tag: `pawtrack-alert-${Date.now()}`,
      data: { url: url ?? '/', resolveCheckNotificationId },
      actions,
      requireInteraction: false,
    }),
  )
})

// ── Notification click handler ────────────────────────────────────────────────

self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close()

  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
  const baseUrl: string = (event.notification.data?.url as string | undefined) ?? '/'
  const resolveCheckNotificationId: string | undefined =
    event.notification.data?.resolveCheckNotificationId as string | undefined

  let targetUrl = baseUrl
  if (resolveCheckNotificationId && (event.action === 'resolve-yes' || event.action === 'resolve-no')) {
    targetUrl = `/notifications?resolveCheckNotificationId=${encodeURIComponent(resolveCheckNotificationId)}`
  }

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((windowClients) => {
        // If a tab is already open, focus it and navigate.
        for (const client of windowClients) {
          if ('navigate' in client) {
            return client.focus().then((c) => c?.navigate(targetUrl))
          }
        }
        // Otherwise open a new tab.
        return self.clients.openWindow(targetUrl)
      }),
  )
})
